addSbtPlugin("org.scoverage"    % "sbt-scoverage"        % "2.0.1")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"       % "1.5.10")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.6.2")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.4.6")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("org.scalameta"    % "sbt-mdoc"             % "2.3.3")
